full_rebuild: true
name: 1991 Digitization/Georeference Workflow
author: Jack Tieszen and Andy Rutkowski
version: 
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: markdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
